version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Executing pre-build phase"
  build:
    commands:
      - echo "Executing build phase"
      - npm run build
      - sed -i 's|CHANGE_CURRENT_VERSION||g' appspec.yml
  post_build:
    commands:
      - echo "Executing post-build phase"
      - aws s3 cp index.html s3://my-bucket/index.html

# reports:
#   testReport:
#     files:
#       - '**/test-report.xml'
#     base-directory: 'test/reports'

artifacts:
  files:
    - '**/*'
  name: my-build-artifact
  discard-paths: yes
  base-directory: /tmp/build
