version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AccountID=$(aws sts get-caller-identity --query "Account" --output text)
      - PRODUCT_ECR_NAME=<Product ECR Name>
      - STRESS_ECR_NAME=<Stress ECR Name>
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $AccountID.dkr.ecr.ap-northeast-2.amazonaws.com
      - PRODUCT_URI=$AccountID.dkr.ecr.ap-northeast-2.amazonaws.com/$PRODUCT_ECR_NAME
      - STRESS_URI=$AccountID.dkr.ecr.ap-northeast-2.amazonaws.com/$STRESS_ECR_NAME
      - IMAGE_TAG="latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $PRODUCT_URI:$IMAGE_TAG ./product/
      - docker build -t $STRESS_URI:$IMAGE_TAG ./stress/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $PRODUCT_URI:$IMAGE_TAG
      - docker push $STRESS_URI:$IMAGE_TAG
      - aws ecs update-service --cluster <ECS Cluster Name> --service <ECS Producet Service Name> --force-new-deployment
      - aws ecs update-service --cluster <ECS Cluster Name> --service <ECS Stress Service Name> --force-new-deployment